version: "3.7"
services:
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c 'npm install && npm run dev'
    ports:
      - '3000:3000'
    tty: true
  backend:
    build: ./backend
    tty: true
    volumes:
        - ./backend:/var/www/laravel
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
  nginx:
      build:
        context: ./nginx/
        dockerfile: Dockerfile
      ports:
        - 80:80
      tty: true
      restart: always
      depends_on:
        - frontend
        - backend
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro