version: "3.7"
services:
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c 'npm install && npm run dev'
    ports:
      - '3000:3000'
    tty: true
  backend:
    build: ./backend
    tty: true
    volumes:
        - ./backend:/var/www/laravel
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
  # ここから下を追記する
  mysql:
    container_name: ${PROJECT_NAME}-mysql
    image: mysql/mysql-server:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - /var/lib/mysql
    env_file:
      - ./.env
  nginx:
      build:
        context: ./nginx/
        dockerfile: Dockerfile
      ports:
        - 80:80
      tty: true
      restart: always
      depends_on:
        - frontend
        - backend
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
  #phpmyadmin
  phpmyadmin:
    container_name: ${PROJECT_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${PROJECT_NAME}-mysql
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - MEMORY_LIMIT=500M
      - UPLOAD_LIMIT=500M
      - MAX_EXECUTION_TIME=1000
  #メールサーバのコンテナ
  mailhog:
    container_name: ${PROJECT_NAME}-mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"